### ISSUE TITLE
NameError: name 'force_decimal_places' is not defined

### ISSUE THREAD

**Issue by docgonzo2015** [CrypticSignal/video-quality-metrics#36]
Hi!

I alway get an error:

Traceback (most recent call last):
  File "main.py", line 123, in <module>
    size_rounded = force_decimal_places(transcode_size, args.decimal_places)
NameError: name 'force_decimal_places' is not defined

Any Idea?

**Comment by CrypticSignal** [comment]
I fixed this issue recently. An import was missing. See: https://github.com/CrypticSignal/video-quality-metrics/commit/22c620113723e293392a15edec5e8971766f5ba1

Pull the latest code and you will no longer run into this issue 🙂

**Comment by docgonzo2015** [comment]
here is also a fix: File "main.py", line 103
    elif video_encoder == 'libaom-av1'  -> elif video_encoder == 'libaom-av1':

Now it get: File "main.py", line 211, in <module>
    log.info(f'All done! Check out the contents of the "{Path(output_folder).parent}" directory.')
NameError: name 'output_folder' is not defined

**Comment by CrypticSignal** [comment]
> here is also a fix: File "main.py", line 103
elif video_encoder == 'libaom-av1' -> elif video_encoder == 'libaom-av1':

Yes, a colon was missing. 
> Now it get: File "main.py", line 211, in
log.info(f'All done! Check out the contents of the "{Path(output_folder).parent}" directory.')
NameError: name 'output_folder' is not defined

I don't see why you ran into that error, nor was I was unable to reproduce that error. I have just pushed a commit where the missing colon has been added, plus other changes: https://github.com/CrypticSignal/video-quality-metrics/commit/cf05480334c2bac60fadb4e55cf8cecb7361a67e. 

Please try again, and report back.
